### PR TITLE
Use bcftools to subsample for individuals

### PR DESCRIPTION
**Pull request by jpuritz**
I was getting an error with the previous version using vcfR "FORMAT" based subsetting.  This seems less prone to errors and faster with loading a potentially smaller VCF file into R.

### CODE REVIEW

**Comment by JimWhiting91** [comment]
Hi Jon, so this issue with out of date packages has cropped up a couple of times and is on my list of things to resolve, at least to give people a better solution than "update R", so thanks for suggesting this! Your suggestion might work but there's a few things that I think would need to be taken into consideration. 

Firstly people have been coming to me with uninterpretable error messages that reflect individuals in `popmap[,1]` that are not in their VCF, so I think this is probably something that will happen often. If this is the case, bcftools won't subset the VCF without --force-samples, but I don't think this is necessarily a big issue.

In addition, the filtering step currently also reorders the individuals according to their order in popmap[,1], which is deliberate. I think though this should also work with bcftools assuming the individuals are parsed in the `popmap[,1]` order? 

The other thing that is cleaner in my opinion would be to make a character string of all individuals separated by commas and parse that to bcftools under the `-s` flag, rather than make a new tempfile. Something along the lines of `inds_to_keep <- paste(popmap[,1],",")`.

The only other step I think in implementing things this way then would be to attach a warning message that states that individuals XYZ are in the popmap but not in the VCF, but I had meaning to do this anyway!

**Comment by jpuritz** [comment]
Hi Jim,

Based on your concerns, I agree that probably a preemptive check for individuals matching the popmap and VCF file would solve a lot of your debugging.  `bcftools query -l` will quickly generate a list of samples within the VCF file.  I think that a quick comparison of the `popmap[,1]` and the output would give you a quick and informative way to check this before even reading in the VCF.  

Your implementation of the `inds_to_keep <- paste(popmap[,1],",")` and using the `-s` is a bit cleaner than another temp file (even if it's only a few kbs).  I still think it makes sense to use `bcftools` to subset the VCF for you, it will save time and memory reading in a smaller VCF file into R.  I don't think it reorders the samples, so I think you will likely need to still do that within R.  I didn't realize this as the VCF I was working with was ordered identically to my `popmap`.

**Comment by JimWhiting91** [comment]
I've had a quick experiment with bcftools and it looks like it will reorder the vcf in the order parsed to -s flag so I think this is probably something we can implement. And yes, I think the bcftools query approach will also work for catching bad popmaps, so if the query output is put into a tmpfile and checked prior to the actual vcf subsetting that should save time. I'll try and get round to this as soon as I can but very busy in the run up to Christmas so sorry if it takes me a little time!

**Comment by JimWhiting91** [comment]
Hi Jon, sorry it took me a while to get round to this. I've updated the package over the weekend based on what we talked about, and bcftools is now used to filter/reorder the vcf following a comparison of the popmap to the output from bcftools query. This resolves a number of issues that people were having so thanks for the suggestion. Apologies for not doing the edits within the pull request and merging, but I had a large list of initial bugs/gripes people were having and I'm still a little new to using github from a collaborative developers perspective, so it felt easier to do these all on my own branch and merge them together. I think I've matched the functionality here though, so I'll close the pull request. Thanks!

**Comment by jpuritz** [comment]
No worries.  Thanks for incorporating the changes.

**Pull request closed without merging**
